# Generated by Django 5.2.6 on 2025-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do ingrediente', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(help_text='Nome da receita', max_length=100, unique=True)),
                ('passos', models.TextField(help_text='Passos para fazer a receita')),
                ('tempo_preparo', models.IntegerField(help_text='Tempo de preparo em minutos')),
                ('ingredientes', models.ManyToManyField(help_text='Ingredientes da receita', to='app.ingrediente')),
            ],
        ),
    ]
